### ISSUE TITLE
Can we run the demo worker as an unprivileged user?

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/demoservice#6]
We may be able to ask rancher to run the demo service workers with the UID of an unprivileged user
https://docs.docker.com/compose/compose-file/#not-supported-for-docker-stack-deploy

This would also solve the problem of having to add `bower install --allow-root` to the ./run script.

**Comment by tbille** [comment]
We are changing the structure of demoservice. Closing since not relevant anymore in the future.
